[package]
name = "pexie"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
tera = "1"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "3.0", features = ["derive", "yaml"] }
dirs = "4"
